-- Regras de despesas fixas/assinaturas. Os lançamentos continuam na tabela
-- despesas, preservando todos os painéis e filtros existentes.
create table if not exists public.despesas_recorrentes (
    id bigint generated by default as identity primary key,
    tipo text not null check (tipo in ('fixa', 'assinatura')),
    data_inicio date not null,
    dia_cobranca smallint not null check (dia_cobranca between 1 and 31),
    categoria text not null,
    descricao text not null check (length(trim(descricao)) > 0),
    valor numeric(12, 2) not null check (valor > 0),
    forma_pagamento text not null default 'Não informado',
    responsavel text not null,
    ativa boolean not null default true,
    desativada_em timestamptz,
    criado_em timestamptz not null default now()
);

alter table public.despesas
    add column if not exists despesa_recorrente_id bigint
        references public.despesas_recorrentes(id) on delete set null,
    add column if not exists competencia date;

create unique index if not exists despesas_recorrencia_competencia_uidx
    on public.despesas (despesa_recorrente_id, competencia)
    where despesa_recorrente_id is not null;

create index if not exists despesas_recorrentes_ativas_idx
    on public.despesas_recorrentes (ativa, dia_cobranca);

-- Gera todas as cobranças já vencidas, inclusive meses não processados enquanto o
-- app esteve desligado. Para dias 29, 30 e 31, usa o último dia do mês quando preciso.
create or replace function public.sincronizar_despesas_recorrentes(
    p_ate date default current_date
)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
    quantidade integer;
begin
    insert into public.despesas (
        data_despesa,
        categoria,
        descricao,
        valor,
        forma_pagamento,
        parcelas,
        responsavel,
        semana,
        despesa_recorrente_id,
        competencia
    )
    select
        cobranca.data_cobranca,
        recorrente.categoria,
        recorrente.descricao,
        recorrente.valor,
        recorrente.forma_pagamento,
        1,
        recorrente.responsavel,
        extract(week from cobranca.data_cobranca)::integer,
        recorrente.id,
        meses.competencia::date
    from public.despesas_recorrentes recorrente
    cross join lateral generate_series(
        date_trunc('month', recorrente.data_inicio)::date,
        date_trunc('month', p_ate)::date,
        interval '1 month'
    ) as meses(competencia)
    cross join lateral (
        select make_date(
            extract(year from meses.competencia)::integer,
            extract(month from meses.competencia)::integer,
            least(
                recorrente.dia_cobranca::integer,
                extract(
                    day from (
                        date_trunc('month', meses.competencia)
                        + interval '1 month - 1 day'
                    )
                )::integer
            )
        ) as data_cobranca
    ) cobranca
    where recorrente.ativa
      and cobranca.data_cobranca >= recorrente.data_inicio
      and cobranca.data_cobranca <= p_ate
    on conflict (despesa_recorrente_id, competencia)
        where despesa_recorrente_id is not null
        do nothing;

    get diagnostics quantidade = row_count;
    return quantidade;
end;
$$;

alter table public.despesas_recorrentes enable row level security;

drop policy if exists "Leitura de despesas recorrentes" on public.despesas_recorrentes;
create policy "Leitura de despesas recorrentes"
    on public.despesas_recorrentes for select
    to anon, authenticated
    using (true);

drop policy if exists "Cadastro de despesas recorrentes" on public.despesas_recorrentes;
create policy "Cadastro de despesas recorrentes"
    on public.despesas_recorrentes for insert
    to anon, authenticated
    with check (true);

drop policy if exists "Atualização de despesas recorrentes" on public.despesas_recorrentes;
create policy "Atualização de despesas recorrentes"
    on public.despesas_recorrentes for update
    to anon, authenticated
    using (true)
    with check (true);

grant select, insert, update on public.despesas_recorrentes to anon, authenticated;
grant usage, select on sequence public.despesas_recorrentes_id_seq to anon, authenticated;
revoke all on function public.sincronizar_despesas_recorrentes(date) from public;
grant execute on function public.sincronizar_despesas_recorrentes(date) to anon, authenticated;
